language: swift
osx_image: xcode9
cache: cocoapods

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - pod repo update
  - gem install slather --no-rdoc --no-ri --no-document --quiet

before_script:
  - swiftlint

script:
  - xcodebuild clean build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' -workspace Sequel.xcworkspace -scheme Sequel

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f Coverage/cobertura.xml -X coveragepy -X gcov -X xcode
