language: swift
osx_image: xcode9

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

before_script:
  - swiftlint

script:
  - xcodebuild clean build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' -workspace SeasonOne.xcworkspace -scheme SeasonOne
